# Dockerfile.dev
FROM node:20

WORKDIR /app

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli

# Copia e instala dependencias
COPY package*.json ./
RUN npm install

# Copia el resto
COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]