version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: angular19-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - devnet
